# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ["--maxkb=4000"]
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.16.2
  hooks:
  - id: cython-lint
  - id: double-quote-cython-strings
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [--config=.flake8]
    files: .*$
    types: [file]
    types_or: [python]
    additional_dependencies: [flake8-force]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python dev/run_pylint.py
      language: python
      types: [python]
      additional_dependencies: [
        pylint>=3.3.1, hatchling, pytest, scikit-learn>=1.5.2, hypothesis, pandas, treelite,
        lightgbm, xgboost>=2.1.1, tqdm
      ]
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: clang-format
      args: ["-i", "--style=file:.clang-format"]
      language: python
      additional_dependencies: [clang-format>=15.0]
      types_or: [c, c++]
    - id: cpplint
      language: python
      args: [
        "--linelength=100", "--recursive",
        "--filter=-build/c++11,-build/include,-build/namespaces_literals,-runtime/references,-build/include_order,+build/include_what_you_use",
        "--root=include"]
      additional_dependencies: [cpplint==1.6.1]
      types_or: [c++]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      additional_dependencies: [types-setuptools, numpy]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
    - id: ruff
      args: ["--config", "python/pyproject.toml"]
